HAI 1.2
I HAS A NUM
VISIBLE "Enter an integer: "
GIMMEH NUM
I HAS A X ITZ A NUM
X R SUM OF NUM AN 10
BOTH SAEM X AN 15, O RLY?
  YA RLY, X R DIFF OF X AN 5
  NO WAI, X R SUM OF X AN 5
OIC
IM IN YR LOOP UPPIN YR X WILE BOTH SAEM SMALR OF X AN 3
VISIBLE X
KTHXBYE
